#+TITLE: Learn VimScript the hard way

* About this Repo
The repo is a walk through of [[http://learnvimscriptthehardway.stevelosh.com][Learn Vimscript the Hard Way]]. The book
is freely distributable providing it is not charged for or modified.
For further details follow the link above.

This repo though, is my vimrc being developed as I walk through the
exercises and my own notes in the form of a README summarising the
main points of each chapter.

* Following the exercises
Each chapter directory will have a vimrc file in it. This will be the
workings for the walk through of the chapter. This file can be loaded
in place of the standard vim configuration file using the command

~vim -u vimrc~

** Troubleshooting / launching vim with defaults

You can load vim without any vimrc file to launch and editor with
vanilla defaults using ~NONE~ as the option for the vimrc file.

~vim -u NONE~

** The Compatability mode trap

If vim launches and detects a ~.vimrc~ file in your home directory it
launches in nocompatable mode. This means it breaks backward
compatability with vi. If you launch vim with the ~-u~ switch either
with a file argument or with ~NONE~ then it will launch in compatible
mode instead. To fix this you have two options

- add ~set nocp~ to the top of your vimscript file to set nocmpatibile
  mode explicitly.
- launch vim with the ~-N~ option this is particulary useful if you
  are lauchning vim without any configuration file ~vim -N -u NONE~.

* What about Emacs?

This format used for learning vim is an excellent way to get to learn
emacs too. As a result this I will endevour to add an Emacs section to
each of the README's explaining how to do an equivalent in Emacs.

It may highlight differences as well as commonalities between the two
editors. It might also describe different ways of achieving similar
effects in Emacs either through Evil mode or a native Emacs solution.

* License
The book written by Steve Losh is subject to his own licensing terms.
Please follow the link above for further clarification.

My own work here is subject to this [[file:LICENSE][repo's license.]]
