#+TITLE: Learn VimScript the hard way

* About this Repo
The repo is a walk through of [[http://learnvimscriptthehardway.stevelosh.com][Learn Vimscript the Hard Way]]. The book
is freely distributable providing it is not charged for or modified.
For further details follow the link above.

This repo though, is my vimrc being developed as I walk through the
exercises and my own notes in the form of a README summarising the
main points of each chapter.

* Following the exercises
Each chapter directory will have a vimrc file in it. This will be the
workings for the walk through of the chapter. This file can be loaded
in place of the standard vim configuration file using the command

~vim -u vimrc~

** Troubleshooting / launching vim with defaults

You can load vim without any vimrc file to launch and editor with
vanilla defaults using ~NONE~ as the option for the vimrc file.

~vim -u NONE~

* License
The book written by Steve Losh is subject to his own licensing terms.
Please follow the link above for further clarification.

My own work here is subject to this [[file:LICENSE][repo's license.]]
